### ISSUE TITLE
other promisify packages?

### ISSUE THREAD

**Issue by fanatid** [sullenor/promisify-api#1]
What's the pros of this package? I think `npm` has dozens same packages...
for example less than week was publish almost the same package (only without receiving context) -- https://www.npmjs.com/package/micro-promisify

BTW, `Array.prototype.slice` for `argumets` is slow and `if-else` probably faster than earlier exit.

**Comment by mightyaleksey** [comment]
Hi,

I spent a lot of time yesterday trying to find out simple and tiny solution for adding promised based interface to functions. I think I checked about 15 or 20 packages. And eventually I ended up with solution of mine. Sounds a little bit wierd, but I wanted to have some insurance and simplicity.

Unfortunately, I haven't seen [micro-promisify](https://www.npmjs.com/package/micro-promisify) earlier.

Anyways, I'm going to adopt that version to nodejs 0.12 version (I need that support for another project), add validation and make few benchmarks (thank you for the tip, I'll check it later).

**Comment by fanatid** [comment]
yep, sometimes `npm` contains shit modules :(
since you've added `context` argument probably will be nice to have a possibility pass other arguments (like `bind` do)

**Comment by mightyaleksey** [comment]
@fanatid can you show the example of usage? Is it similar to `lodash.partial`?

I added context for the object like interfaces, when you want to wrap its method: https://github.com/sullenor/promisify-api/blob/master/test.js#L25-L34

**Comment by fanatid** [comment]
yes, it is similar to `lodash.partial`:

``` js
function f (a, b, cb) { cb(a + b) }
promisify(f, undefined, 1)(2).then(function (x) { console.log(x) }) // 3
```
